[templates.makefile-advanced]
description = "Advanced Makefile with auto-documentation and task grouping (based on Zenn article by loglass)"

required_args = [
    { name = "project_name", description = "Project name" }
]

optional_args = [
    { name = "author", default = "Generated", description = "Author name" },
    { name = "date", default = "{{current_date}}", description = "Creation date" },
    { name = "type", default = "general", description = "Project type (docker/node/go/python/general)" }
]

files = [
    { source = "templates/Makefile", destination = "Makefile" },
    { source = "templates/help.awk", destination = "help.awk" }
]

[templates.github-actions-ci]
description = "GitHub Actions CI/CD workflow with tests, build, and deployment"

required_args = [
    { name = "type", description = "Project type (node, go, python, dotnet)" },
    { name = "name", description = "Workflow name (e.g., ci, test-and-build)" }
]

optional_args = [
    { name = "author", default = "Generated", description = "Author name" },
    { name = "date", default = "{{current_date}}", description = "Creation date" },
    { name = "node_version", default = "20", description = "Node.js version" },
    { name = "go_version", default = "1.23", description = "Go version" },
    { name = "python_version", default = "3.12", description = "Python version" },
    { name = "dotnet_version", default = "8.0.x", description = ".NET version" }
]

files = [
    { source = "templates/{{type}}-ci.yml", destination = ".github/workflows/{{name}}.yml" }
]